---
- name: Verify
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Verify that cmake is installed
      shell: "/usr/local/bin/cmake --version"
      args:
        executable: /bin/bash
      changed_when: False
      environment:
        BASH_ENV: "{{ ansible_env.HOME }}/.bashrc"

# vim: set ft=yaml.ansible :
